### レジストリに登録されるイメージはx86のみですので、Macでは動作しません。
services:
  web:
    image: ${REGISTRY}:latest
    ports:
      - "5001:5001"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.shopping-to-b2.tls=true"
      - "traefik.http.routers.shopping-to-b2.service=shopping-to-b2"
      - "traefik.http.routers.shopping-to-b2.rule=Host(`${TS_HOST}`)"
      - "traefik.http.routers.shopping-to-b2.tls.certresolver=tsresolver"
      - "traefik.http.services.shopping-to-b2.loadbalancer.server.port=5001"
    networks:
      - traefik

networks:
  traefik:
    name: traefik_net
    external: true